### ISSUE TITLE
Attention au vol de mot-croisillon : une liste de blocage ?

### ISSUE THREAD

**Issue by bortzmeyer** [Meewan/MercrediFiction#4]
Il serait bon, je crois, de virer certains pouètes qui utilisent le mot-croisillon #MercrediFiction mais n'en sont pas. Par exemple ceux de TrendingBot@mastodon.social

**Comment by Meewan** [comment]
oui, un système de blacklist est prévu. Mais en dehors de blacklister a la main les auteur ou les pouets je vois pas comment faire.

je vais ajouter un ensemble de scripts pour commander tout ce bazar (faire a la main est vite lourd)

**Comment by bortzmeyer** [comment]
Oui, je pense que la liste de blocage doit être gérée manuellement (et avec une main légère : il vaut mieux quelques pouètes hors-sujet que de bloquer des bons pouètes).

**Comment by Meewan** [comment]
Ce sera dans la prochaine release (probablement demain)

**Comment by Meewan** [comment]
done
